### ISSUE TITLE
nested array in result

### ISSUE THREAD

**Issue by matiazar** [lukascivil/TreeWalker#5]
HI, thanks for this fantastic code... 

i have a litlle problem.
Im receiving this answer with this
$treewalker->getdiff($json1, $json2);

array:3 [▼
  "new" => array:63 [▼
    "shipping/id" => "123456"

how can i do to receive the array like array ?

array:3 [▼
  "new" => array:63 [▼
    "shipping" => array [
         "id" => "21665181130"

thanks !!

**Comment by lukascivil** [comment]
Matiazar, thank you very much for your comment. Could you paste here the input objects? So i can take a test and analyze the problem. However, by analyzing your post, I see that shipping is the parent of id, so the (output, result) is right, because the nesting of objects in the result is done by "/", it was our pattern. If you want "parent: {child: value}" instead of "parent/child: value", you can create a simple code that identifies "/" and convert to object, pattern that you want. I do not know if i answered you, if you have more doubts please post the "issue"s.
