### ISSUE TITLE
array con indices numericos

### ISSUE THREAD

**Issue by matiazar** [lukascivil/TreeWalker#6]
en la linea 188 dice

if ($key != "_id") {

deberia decir

if ($key !== "_id") {

porque si viene un array con indices numericos
por ej

nombres = ['juan', 'ramon', 'gonzalo']

al hacer el diff devuelve

nombres/ = juan
nombres/1/ = ramon
nombres/2/ = gonzalo

**Comment by lukascivil** [comment]
I saw this part of the code, it was an unnecessary part that was used to solve an old problem. I removed this. And,

**i did the test with:**

"nombres" => array("juan", "ramon", 'gonzalo)

**and the result was :**

"nombres/0": "juan",
"nombres/1": "ramon",
"nombres/2": "gonzalo",

The logic is ok, because in array not associative you have the numeric keys.
Understood?
